#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    if [ ! -x "/usr/bin/netflow" ]; then
        logger -t netflow "binary not found: /usr/bin/netflow"
        return 1
    fi

    procd_open_instance
    procd_set_param command /usr/bin/netflow
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    logger -t netflow "service started"
}

stop_service() {
    logger -t netflow "service stopping"
}

service_triggers() {
    procd_add_reload_trigger "netflow"
}
